pipelines:
  default:
    - parallel:
        - step:
            image: bats/bats:1.9.0
            name: 'Build and Test'
            script:
              - echo "Running tests...."
              - test --timing --pretty
        - step:
            image: koalaman/shellcheck-alpine:v0.9.0
            name: 'Shell Lint'
            script:
              - echo "Linting shell scripts"
              - shellcheck **/*.sh **/*.bats
        - step:
            image: hadolint/hadolint:v2.12.0-alpine
            name: 'Docker Lint'
            script:
              - echo "Linting Dockerfile(s)"
              - hadolint Dockerfile
    - step:
        name: 'Deployment to Staging'
        deployment: staging
        script:
          - echo "Plachholder - Deploy to Staging"
    - step:
        name: 'Deployment to Production'
        deployment: production
        trigger: 'manual'
        script:
          - echo "Plachholder - Deploy to Staging"