name: Lint Dockerfiles

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: hadolint/hadolint:v2.12.0-alpine

    steps:
      - uses: actions/checkout@v3
      - name: Lint the Dockerfile
        run: hadolint Dockerfile
